### ISSUE TITLE
/node/<node_id>/transmissions gives error

### ISSUE THREAD

**Issue by suchow** [suchow/Wallace#335]
```
Traceback (most recent call last):
  File "/Users/jordansuchow/.virtualenvs/wallace/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jordansuchow/.virtualenvs/wallace/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jordansuchow/.virtualenvs/wallace/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jordansuchow/.virtualenvs/wallace/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jordansuchow/.virtualenvs/wallace/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/private/var/folders/9l/s_hqlr1520s24xp9wz0g5k2m0000gn/T/tmpXcUnnC/w1cac4a42-ea75-4fe7-8864-694b/custom.py", line 873, in node_transmissions
    transmissions = node.transmissions(direction=direction, status=status)
  File "/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Wallace/wallace/models.py", line 793, in transmissions
    "Type can only be incoming, outgoing or all."))
ValueError: You cannot get transmissions of direction to.Type can only be incoming, outgoing or all.
```

This happens even though direction "to" was not requested.

**Comment by thomasmorgan** [comment]
fixed. It was a bad default value. I have changed "to" to "incoming".
